import { PrismaClient, Role } from '@prisma/client';
import bcrypt from 'bcryptjs';

const prisma = new PrismaClient();

async function main() {
  console.log('🌱 Seeding database...');

  // Create tenants
  const tenantA = await prisma.tenant.upsert({
    where: { slug: 'alpha-flight' },
    update: {},
    create: {
      name: 'Alpha Flight School',
      slug: 'alpha-flight',
    },
  });

  const tenantB = await prisma.tenant.upsert({
    where: { slug: 'bravo-aviation' },
    update: {},
    create: {
      name: 'Bravo Aviation Academy',
      slug: 'bravo-aviation',
    },
  });

  const hash = (pw: string) => bcrypt.hashSync(pw, 10);

  // Tenant A users
  const adminA = await prisma.user.upsert({
    where: { email_tenantId: { email: 'admin@alpha.com', tenantId: tenantA.id } },
    update: {},
    create: {
      email: 'admin@alpha.com',
      passwordHash: hash('Admin@123'),
      firstName: 'Alice',
      lastName: 'Admin',
      role: Role.ADMIN,
      isApproved: true,
      tenantId: tenantA.id,
    },
  });

  const instructorA = await prisma.user.upsert({
    where: { email_tenantId: { email: 'instructor@alpha.com', tenantId: tenantA.id } },
    update: {},
    create: {
      email: 'instructor@alpha.com',
      passwordHash: hash('Instructor@123'),
      firstName: 'Ivan',
      lastName: 'Instructor',
      role: Role.INSTRUCTOR,
      isApproved: true,
      tenantId: tenantA.id,
    },
  });

  const studentA = await prisma.user.upsert({
    where: { email_tenantId: { email: 'student@alpha.com', tenantId: tenantA.id } },
    update: {},
    create: {
      email: 'student@alpha.com',
      passwordHash: hash('Student@123'),
      firstName: 'Sam',
      lastName: 'Student',
      role: Role.STUDENT,
      isApproved: true,
      tenantId: tenantA.id,
    },
  });

  // Tenant B users
  await prisma.user.upsert({
    where: { email_tenantId: { email: 'admin@bravo.com', tenantId: tenantB.id } },
    update: {},
    create: {
      email: 'admin@bravo.com',
      passwordHash: hash('Admin@123'),
      firstName: 'Bob',
      lastName: 'Admin',
      role: Role.ADMIN,
      isApproved: true,
      tenantId: tenantB.id,
    },
  });

  // Sample course
  const course = await prisma.course.upsert({
    where: { id: 'seed-course-1' },
    update: {},
    create: {
      id: 'seed-course-1',
      title: 'Private Pilot Ground School',
      description: 'Complete ground school curriculum for PPL candidates',
      tenantId: tenantA.id,
      instructorId: instructorA.id,
      isPublished: true,
    },
  });

  const module1 = await prisma.module.upsert({
    where: { id: 'seed-module-1' },
    update: {},
    create: {
      id: 'seed-module-1',
      title: 'Aviation Fundamentals',
      courseId: course.id,
      order: 1,
    },
  });

  const textLesson = await prisma.lesson.upsert({
    where: { id: 'seed-lesson-1' },
    update: {},
    create: {
      id: 'seed-lesson-1',
      title: 'Four Forces of Flight',
      type: 'TEXT',
      content: `## The Four Forces of Flight\n\nFlight is possible due to four fundamental forces:\n\n**Lift** – Generated by wings, opposes weight.\n**Weight** – Gravity pulling the aircraft down.\n**Thrust** – Engine propulsion moving the aircraft forward.\n**Drag** – Air resistance opposing motion.\n\nFor level flight, Lift = Weight and Thrust = Drag.`,
      moduleId: module1.id,
      order: 1,
    },
  });

  const quizLesson = await prisma.lesson.upsert({
    where: { id: 'seed-lesson-2' },
    update: {},
    create: {
      id: 'seed-lesson-2',
      title: 'Forces of Flight Quiz',
      type: 'QUIZ',
      moduleId: module1.id,
      order: 2,
    },
  });

  const quiz = await prisma.quiz.upsert({
    where: { lessonId: quizLesson.id },
    update: {},
    create: {
      lessonId: quizLesson.id,
    },
  });

  await prisma.question.upsert({
    where: { id: 'seed-q-1' },
    update: {},
    create: {
      id: 'seed-q-1',
      quizId: quiz.id,
      text: 'Which force opposes the weight of an aircraft?',
      options: ['Thrust', 'Lift', 'Drag', 'Inertia'],
      correctAnswer: 1,
      order: 1,
    },
  });

  await prisma.question.upsert({
    where: { id: 'seed-q-2' },
    update: {},
    create: {
      id: 'seed-q-2',
      quizId: quiz.id,
      text: 'In level unaccelerated flight, Thrust equals:',
      options: ['Lift', 'Weight', 'Drag', 'Gravity'],
      correctAnswer: 2,
      order: 2,
    },
  });

  // Sample availability
  const tomorrow = new Date();
  tomorrow.setDate(tomorrow.getDate() + 1);
  tomorrow.setHours(9, 0, 0, 0);
  const tomorrowEnd = new Date(tomorrow);
  tomorrowEnd.setHours(17, 0, 0, 0);

  await prisma.instructorAvailability.create({
    data: {
      instructorId: instructorA.id,
      tenantId: tenantA.id,
      startTime: tomorrow,
      endTime: tomorrowEnd,
    },
  });

  console.log('✅ Seed complete!');
  console.log('\n📋 Demo Credentials:');
  console.log('  Tenant A (Alpha Flight School):');
  console.log('    Admin:      admin@alpha.com / Admin@123');
  console.log('    Instructor: instructor@alpha.com / Instructor@123');
  console.log('    Student:    student@alpha.com / Student@123');
  console.log('  Tenant B (Bravo Aviation):');
  console.log('    Admin:      admin@bravo.com / Admin@123');
}

main()
  .catch(console.error)
  .finally(() => prisma.$disconnect());
